# Utilisation de l'image PHP avec Apache
FROM php:5-apache

# Définition des variables d'environnement (peut aussi être fait via docker-compose ou la commande docker run)
ENV MYSQL_HOST=172.17.0.2
ENV MYSQL_ROOT_PASSWORD=root

# Copie des fichiers de votre application dans le conteneur
COPY ./www/ /var/www/html/
RUN chmod -R 777 /var/www/html/uploads
RUN docker-php-ext-install mysqli

# Exposition du port 80
EXPOSE 80



